package AnaliseLexica;


public enum Token {
    BEGIN, END, OPERADOR_ARITMETICO, COND_IF, COND_ELIF, COND_ELSE, ABRE_PARENTESES, FECHA_PARENTESES, ABRE_CHAVES, FECHA_CHAVES, ABRE_COLCHETES, FECHA_COLCHETES,
    WHILE, BOOLEAN, TIPOS_PRIMITIVOS, VAR, PONTO_VIRGULA, DOIS_PONTOS, PRINT, TEXTO, OPERADOR_LOGICO, OPERADOR_CONDICIONAL, ATRIBUICAO, QUEBRA_LINHA, ERRO,
    NUMERO, ESPACO, PONTO, COMENTARIO_BLOCO, COMENTARIO_LINHA, VIRGULA;
}
