
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 16 17:47:13 BRT 2019
//----------------------------------------------------

package AnaliseSintatica;

import java.io.*;
import java_cup.runtime.*;
import AnaliseSintatica.Yylex;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu May 16 17:47:13 BRT 2019
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\004\000\002\002" +
    "\005\000\002\003\003\000\002\003\003\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\004\005\000" +
    "\002\004\006\000\002\006\006\000\002\006\007\000\002" +
    "\006\006\000\002\006\007\000\002\006\006\000\002\006" +
    "\007\000\002\006\010\000\002\006\011\000\002\005\007" +
    "\000\002\005\010\000\002\005\007\000\002\005\007\000" +
    "\002\005\010\000\002\005\007\000\002\005\007\000\002" +
    "\005\010\000\002\005\007\000\002\005\011\000\002\005" +
    "\012\000\002\005\011\000\002\011\007\000\002\011\010" +
    "\000\002\011\007\000\002\011\010\000\002\014\006\000" +
    "\002\014\007\000\002\014\006\000\002\014\007\000\002" +
    "\013\005\000\002\013\005\000\002\013\005\000\002\007" +
    "\007\000\002\007\007\000\002\007\012\000\002\007\007" +
    "\000\002\007\007\000\002\007\007\000\002\007\007\000" +
    "\002\007\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\004\004\004\001\002\000\012\005\020\022" +
    "\014\023\013\026\015\001\002\000\004\002\006\001\002" +
    "\000\004\002\001\001\002\000\004\005\ufffc\001\002\000" +
    "\004\005\165\001\002\000\004\005\ufffe\001\002\000\004" +
    "\005\ufffa\001\002\000\004\032\100\001\002\000\004\023" +
    "\032\001\002\000\004\012\021\001\002\000\004\005\ufffb" +
    "\001\002\000\004\005\ufffd\001\002\000\004\002\000\001" +
    "\002\000\006\023\023\027\022\001\002\000\004\013\027" +
    "\001\002\000\004\013\024\001\002\000\004\024\025\001" +
    "\002\000\012\005\uffe1\022\014\023\013\026\015\001\002" +
    "\000\004\005\uffe0\001\002\000\004\024\030\001\002\000" +
    "\012\005\uffe3\022\014\023\013\026\015\001\002\000\004" +
    "\005\uffe2\001\002\000\006\024\033\032\034\001\002\000" +
    "\012\005\ufff9\022\014\023\013\026\015\001\002\000\010" +
    "\021\037\027\035\035\036\001\002\000\006\024\074\042" +
    "\075\001\002\000\010\024\064\037\065\042\066\001\002" +
    "\000\006\024\040\042\041\001\002\000\004\005\uffe9\001" +
    "\002\000\006\022\043\023\042\001\002\000\004\032\046" +
    "\001\002\000\004\023\045\001\002\000\004\005\uffe8\001" +
    "\002\000\004\032\034\001\002\000\010\021\051\027\047" +
    "\035\050\001\002\000\004\042\062\001\002\000\006\037" +
    "\054\042\055\001\002\000\004\042\052\001\002\000\006" +
    "\022\043\023\042\001\002\000\004\005\uffe7\001\002\000" +
    "\004\035\057\001\002\000\006\022\043\023\042\001\002" +
    "\000\004\005\uffea\001\002\000\004\042\060\001\002\000" +
    "\006\022\043\023\042\001\002\000\004\005\uffe4\001\002" +
    "\000\006\022\043\023\042\001\002\000\004\005\uffed\001" +
    "\002\000\004\005\uffec\001\002\000\004\035\070\001\002" +
    "\000\006\022\043\023\042\001\002\000\004\005\uffeb\001" +
    "\002\000\006\024\071\042\072\001\002\000\004\005\uffe6" +
    "\001\002\000\006\022\043\023\042\001\002\000\004\005" +
    "\uffe5\001\002\000\004\005\uffef\001\002\000\006\022\043" +
    "\023\042\001\002\000\004\005\uffee\001\002\000\004\005" +
    "\ufff8\001\002\000\014\012\105\021\107\023\102\027\103" +
    "\035\101\001\002\000\012\006\133\024\157\037\160\042" +
    "\055\001\002\000\004\006\155\001\002\000\006\024\153" +
    "\042\062\001\002\000\004\024\151\001\002\000\006\012" +
    "\116\035\114\001\002\000\004\024\112\001\002\000\006" +
    "\024\110\042\052\001\002\000\012\005\ufff3\022\014\023" +
    "\013\026\015\001\002\000\004\005\ufff2\001\002\000\012" +
    "\005\uffdf\022\014\023\013\026\015\001\002\000\004\005" +
    "\uffde\001\002\000\004\006\146\001\002\000\004\006\137" +
    "\001\002\000\006\012\116\035\117\001\002\000\004\006" +
    "\120\001\002\000\010\012\105\023\102\035\121\001\002" +
    "\000\006\006\133\013\136\001\002\000\010\013\127\023" +
    "\102\035\125\001\002\000\004\013\124\001\002\000\014" +
    "\006\uffd7\013\uffd7\023\uffd7\024\uffd7\035\uffd7\001\002\000" +
    "\004\006\133\001\002\000\006\012\130\013\131\001\002" +
    "\000\014\006\uffd5\013\uffd5\023\uffd5\024\uffd5\035\uffd5\001" +
    "\002\000\004\013\132\001\002\000\014\006\uffd1\013\uffd1" +
    "\023\uffd1\024\uffd1\035\uffd1\001\002\000\014\006\uffd6\013" +
    "\uffd6\023\uffd6\024\uffd6\035\uffd6\001\002\000\006\023\102" +
    "\035\134\001\002\000\012\006\133\012\uffdb\013\uffdb\024" +
    "\uffdb\001\002\000\010\012\uffda\013\uffda\024\uffda\001\002" +
    "\000\014\006\uffd8\013\uffd8\023\uffd8\024\uffd8\035\uffd8\001" +
    "\002\000\010\012\105\023\102\035\140\001\002\000\006" +
    "\006\133\013\145\001\002\000\004\013\144\001\002\000" +
    "\004\013\143\001\002\000\014\006\uffd2\013\uffd2\023\uffd2" +
    "\024\uffd2\035\uffd2\001\002\000\014\006\uffd3\013\uffd3\023" +
    "\uffd3\024\uffd3\035\uffd3\001\002\000\014\006\uffd4\013\uffd4" +
    "\023\uffd4\024\uffd4\035\uffd4\001\002\000\010\012\105\023" +
    "\102\035\121\001\002\000\010\013\127\023\102\035\125" +
    "\001\002\000\004\013\131\001\002\000\012\005\uffdd\022" +
    "\014\023\013\026\015\001\002\000\004\005\uffdc\001\002" +
    "\000\012\005\ufff5\022\014\023\013\026\015\001\002\000" +
    "\004\005\ufff4\001\002\000\006\023\102\035\125\001\002" +
    "\000\010\012\uffd9\013\uffd9\024\uffd9\001\002\000\012\005" +
    "\ufff7\022\014\023\013\026\015\001\002\000\004\035\161" +
    "\001\002\000\006\024\162\042\060\001\002\000\012\005" +
    "\ufff1\022\014\023\013\026\015\001\002\000\004\005\ufff0" +
    "\001\002\000\004\005\ufff6\001\002\000\004\002\uffff\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\163\000\004\002\004\001\001\000\016\003\007\004" +
    "\010\005\006\006\016\011\015\014\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\003" +
    "\025\004\010\005\006\006\016\011\015\014\011\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\003\030\004" +
    "\010\005\006\006\016\011\015\014\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\016\003\076\004\010\005" +
    "\006\006\016\011\015\014\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\043\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\005\052\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\005\055\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\005\060\001\001\000\002\001" +
    "\001\000\004\005\062\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\005\066\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\005\072\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\075\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\007\103\013\105\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\007\114\001\001\000\002\001\001\000\002\001\001\000" +
    "\016\003\110\004\010\005\006\006\016\011\015\014\011" +
    "\001\001\000\002\001\001\000\016\003\112\004\010\005" +
    "\006\006\016\011\015\014\011\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\114\001" +
    "\001\000\002\001\001\000\006\007\121\013\122\001\001" +
    "\000\002\001\001\000\004\013\125\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\134\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\007\140\013" +
    "\141\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\007\146\013\122\001\001\000\004\013\147" +
    "\001\001\000\002\001\001\000\016\003\151\004\010\005" +
    "\006\006\016\011\015\014\011\001\001\000\002\001\001" +
    "\000\016\003\153\004\010\005\006\006\016\011\015\014" +
    "\011\001\001\000\002\001\001\000\004\013\155\001\001" +
    "\000\002\001\001\000\016\003\163\004\010\005\006\006" +
    "\016\011\015\014\011\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\003\162\004\010\005\006\006\016\011" +
    "\015\014\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        public Symbol s;

	/*public static void main (String args[]) throws Exception{
		//new parser(new Yylex(new FileInputStream(args[0]))).parse();
		new parser(new Yylex(System.in)).parse();
	}*/
	
	public void syntax_error(Symbol s){
                this.s = s;
		report_error("Error de sintaxis. Linha: " +(s.right + 1) +
		" Coluna: " + s.left + ". Texto: \"" + s.value + "\"", null);
       // public static void carregar(String arquivo) throws Exception{
       // new parser(new Yylex(new FileInputStream(arquivo))).parse();
        }

        public Symbol getS () {
            return s;
        }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES NUMERO OPERADOR_ARITMETICO operacao_aritmetica_parenteses operacao_aritmetica FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES operacao_aritmetica_parenteses OPERADOR_ARITMETICO operacao_aritmetica FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES operacao_aritmetica_parenteses OPERADOR_ARITMETICO operacao_aritmetica_parenteses FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES operacao_aritmetica_parenteses OPERADOR_ARITMETICO NUMERO FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES NUMERO OPERADOR_ARITMETICO operacao_aritmetica_parenteses FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES ABRE_PARENTESES NUMERO OPERADOR_ARITMETICO operacao_aritmetica_parenteses operacao_aritmetica ABRE_PARENTESES FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES NUMERO OPERADOR_ARITMETICO operacao_aritmetica FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // operacao_aritmetica_parenteses ::= ABRE_PARENTESES NUMERO OPERADOR_ARITMETICO NUMERO FECHA_PARENTESES 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica_parenteses",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // operacao_aritmetica ::= VAR OPERADOR_ARITMETICO operacao_aritmetica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // operacao_aritmetica ::= NUMERO OPERADOR_ARITMETICO operacao_aritmetica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // operacao_aritmetica ::= NUMERO OPERADOR_ARITMETICO NUMERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operacao_aritmetica",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expressao_aritmetica ::= VAR ATRIBUICAO operacao_aritmetica_parenteses PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao_aritmetica",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expressao_aritmetica ::= VAR ATRIBUICAO operacao_aritmetica_parenteses PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao_aritmetica",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expressao_aritmetica ::= VAR ATRIBUICAO operacao_aritmetica PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao_aritmetica",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expressao_aritmetica ::= VAR ATRIBUICAO operacao_aritmetica PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao_aritmetica",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // escrever ::= PRINT ABRE_PARENTESES VAR FECHA_PARENTESES PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("escrever",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // escrever ::= PRINT ABRE_PARENTESES VAR FECHA_PARENTESES PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("escrever",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // escrever ::= PRINT ABRE_PARENTESES TEXTO FECHA_PARENTESES PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("escrever",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // escrever ::= PRINT ABRE_PARENTESES TEXTO FECHA_PARENTESES PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("escrever",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declaracao_atribuicao ::= VAR ATRIBUICAO NUMERO PONTO NUMERO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO NUMERO PONTO NUMERO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO NUMERO PONTO NUMERO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // declaracao_atribuicao ::= VAR ATRIBUICAO BOOLEAN VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO BOOLEAN VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO BOOLEAN PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracao_atribuicao ::= VAR ATRIBUICAO NUMERO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO NUMERO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO NUMERO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaracao_atribuicao ::= VAR ATRIBUICAO TEXTO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO TEXTO VIRGULA declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracao_atribuicao ::= TIPOS_PRIMITIVOS VAR ATRIBUICAO TEXTO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao_atribuicao",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // atribuicao ::= VAR ATRIBUICAO NUMERO PONTO NUMERO PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // atribuicao ::= VAR ATRIBUICAO NUMERO PONTO NUMERO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // atribuicao ::= VAR ATRIBUICAO BOOLEAN PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // atribuicao ::= VAR ATRIBUICAO BOOLEAN PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // atribuicao ::= VAR ATRIBUICAO TEXTO PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // atribuicao ::= VAR ATRIBUICAO TEXTO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // atribuicao ::= VAR ATRIBUICAO NUMERO PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // atribuicao ::= VAR ATRIBUICAO NUMERO PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracao ::= TIPOS_PRIMITIVOS VAR PONTO_VIRGULA programa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracao ::= TIPOS_PRIMITIVOS VAR PONTO_VIRGULA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // programa ::= expressao_aritmetica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // programa ::= escrever 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // programa ::= declaracao_atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // programa ::= atribuicao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= declaracao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= BEGIN programa END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= BEGIN END 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

