
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 20 15:59:13 BRT 2019
//----------------------------------------------------

package AnaliseSintatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FECHA_COLCHETES = 13;
  public static final int NUMERO = 27;
  public static final int IFMUZ = 35;
  public static final int ERRO = 26;
  public static final int FOR = 34;
  public static final int DOIS_PONTOS = 19;
  public static final int VIRGULA = 32;
  public static final int COMENTARIO_LINHA = 31;
  public static final int PONTO = 29;
  public static final int BEGIN = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 15;
  public static final int ESPACO = 28;
  public static final int PONTO_VIRGULA = 18;
  public static final int ABRE_PARENTESES = 8;
  public static final int error = 1;
  public static final int COMENTARIO_BLOCO = 30;
  public static final int OPERADOR_LOGICO = 22;
  public static final int OPERADOR_LOGICO_NOT = 33;
  public static final int ABRE_COLCHETES = 12;
  public static final int COND_ELSE = 7;
  public static final int OPERADOR_ARITMETICO = 4;
  public static final int QUEBRA_LINHA = 25;
  public static final int WHILE = 14;
  public static final int TIPOS_PRIMITIVOS = 16;
  public static final int FECHA_PARENTESES = 9;
  public static final int ATRIBUICAO = 24;
  public static final int END = 3;
  public static final int ABRE_CHAVES = 10;
  public static final int TEXTO = 21;
  public static final int COND_IF = 5;
  public static final int OPERADOR_CONDICIONAL = 23;
  public static final int FECHA_CHAVES = 11;
  public static final int VAR = 17;
  public static final int COND_ELIF = 6;
  public static final int PRINT = 20;
}

